name: Metrics
on:
  schedule:
    - cron: "0 0-23/4 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: 🦑 Personal metrics (left)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          config_order: base.header, isocalendar, languages

      - name: 🦑 Personal metrics (right)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.anilist.svg
          token: NOT_NEEDED
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga             # Display both animes and mangas
          plugin_anilist_sections: favorites, characters  # Display only favorites and characters sections
          plugin_anilist_limit: 2                         # Limit to 2 entry per section (characters section excluded)
          plugin_anilist_shuffle: yes                     # Shuffle data for more varied outputs
          plugin_anilist_user: .user.login                # Use same username as GitHub login
          plugin_anilist_limit_characters: 22             # Limit to 22 characters in characters section

      - name: 🦑 Personal metrics (bottom)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          config_display: large
          
